#!/bin/bash 

function server_second_level_cert_and_key_java_client_second_level_cert_success()
{
 killall server &> /dev/null
 ../server/server ../server/foo-cert.pem ../server/foo-key.pem &> /dev/null &

 sleep 1
 CLIENT_OUT=$(cd ../java-client && java SslClient ../server/foo-cert.pem)
 
 echo $CLIENT_OUT | grep -q "I hear you" && echo $0 "Success" || echo $1 "Failure"
}

function server_second_level_cert_and_key_java_client_first_level_cert_success()
{
 killall server &> /dev/null
 ../server/server ../server/foo-cert.pem ../server/foo-key.pem &> /dev/null &

 sleep 1
 CLIENT_OUT=$(cd ../java-client && java SslClient ../ca/ca-cert.pem)
 
 echo $CLIENT_OUT | grep -q "I hear you" && echo $0 "Success" || echo $1 "Failure"
}

server_second_level_cert_and_key_java_client_second_level_cert_success
server_second_level_cert_and_key_java_client_first_level_cert_success
